image:
  - Visual Studio 2017
  - Visual Studio 2019
  - Visual Studio 2022
  - Ubuntu

configuration:
  - Debug
  - Release

environment:
  matrix:
    - SHARED: true
    - SHARED: false

platform:
    - x64

for:
  -
    install:
      - python -m pip install conan cmake
      - conan profile detect
      - cmake --version
    test_script:
      - conan create . -s build_type=%CONFIGURATION% -c tools.build:skip_test=False -o shared=%SHARED%
