image:
  - Visual Studio 2017
  - Visual Studio 2019
  - Visual Studio 2022

configuration:
  - Debug
  - Release

environment:
  PYTHON: "C:\\Python38-x64"
  PY_SCRIPTS: "C:\\Python38-x64\\Scripts"
  
  matrix:
    - SHARED: True
    - SHARED: False

platform:
    - x64

for:
  -
    install:
      - set PATH=%PY_SCRIPTS%;%PATH%
      - echo %PATH%
      - "%PYTHON%\\python.exe -m pip install conan cmake"
    build_script:
      - cmake --version
      - conan profile detect
    test_script:
      - conan create . -s build_type=%CONFIGURATION% -s compiler.cppstd=17 -c tools.build:skip_test=False -o shared=%SHARED% --version 0.26
